/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win_dutoe_TestCCA */

#ifndef _Included_win_dutoe_TestCCA
#define _Included_win_dutoe_TestCCA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win_dutoe_TestCCA
 * Method:    libIceAnalysis
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_win_dutoe_TestCCA_libIceAnalysis
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
